/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ClaimRouteRouteImport } from './routes/claim/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ReportFormRoutesRouteImport } from './routes/report-form/routes'
import { Route as HomeRoutesRouteImport } from './routes/home/routes'
import { Route as HeaderRoutesRouteImport } from './routes/header/routes'
import { Route as FooterRoutesRouteImport } from './routes/footer/routes'
import { Route as ClaimClaimFormRouteImport } from './routes/claim/claimForm'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminDashboardVerifyRouteImport } from './routes/admin/dashboard/verify'
import { Route as AdminDashboardReportsRouteImport } from './routes/admin/dashboard/reports'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRouteRoute = ClaimRouteRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportFormRoutesRoute = ReportFormRoutesRouteImport.update({
  id: '/report-form/routes',
  path: '/report-form/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoutesRoute = HomeRoutesRouteImport.update({
  id: '/home/routes',
  path: '/home/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderRoutesRoute = HeaderRoutesRouteImport.update({
  id: '/header/routes',
  path: '/header/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterRoutesRoute = FooterRoutesRouteImport.update({
  id: '/footer/routes',
  path: '/footer/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimClaimFormRoute = ClaimClaimFormRouteImport.update({
  id: '/claimForm',
  path: '/claimForm',
  getParentRoute: () => ClaimRouteRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/admin/dashboard/',
  path: '/admin/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardVerifyRoute = AdminDashboardVerifyRouteImport.update({
  id: '/admin/dashboard/verify',
  path: '/admin/dashboard/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardReportsRoute = AdminDashboardReportsRouteImport.update({
  id: '/admin/dashboard/reports',
  path: '/admin/dashboard/reports',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claim': typeof ClaimRouteRouteWithChildren
  '/report': typeof ReportRoute
  '/claim/claimForm': typeof ClaimClaimFormRoute
  '/footer/routes': typeof FooterRoutesRoute
  '/header/routes': typeof HeaderRoutesRoute
  '/home/routes': typeof HomeRoutesRoute
  '/report-form/routes': typeof ReportFormRoutesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard/reports': typeof AdminDashboardReportsRoute
  '/admin/dashboard/verify': typeof AdminDashboardVerifyRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claim': typeof ClaimRouteRouteWithChildren
  '/report': typeof ReportRoute
  '/claim/claimForm': typeof ClaimClaimFormRoute
  '/footer/routes': typeof FooterRoutesRoute
  '/header/routes': typeof HeaderRoutesRoute
  '/home/routes': typeof HomeRoutesRoute
  '/report-form/routes': typeof ReportFormRoutesRoute
  '/admin': typeof AdminIndexRoute
  '/admin/dashboard/reports': typeof AdminDashboardReportsRoute
  '/admin/dashboard/verify': typeof AdminDashboardVerifyRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claim': typeof ClaimRouteRouteWithChildren
  '/report': typeof ReportRoute
  '/claim/claimForm': typeof ClaimClaimFormRoute
  '/footer/routes': typeof FooterRoutesRoute
  '/header/routes': typeof HeaderRoutesRoute
  '/home/routes': typeof HomeRoutesRoute
  '/report-form/routes': typeof ReportFormRoutesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard/reports': typeof AdminDashboardReportsRoute
  '/admin/dashboard/verify': typeof AdminDashboardVerifyRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claim'
    | '/report'
    | '/claim/claimForm'
    | '/footer/routes'
    | '/header/routes'
    | '/home/routes'
    | '/report-form/routes'
    | '/admin/'
    | '/admin/dashboard/reports'
    | '/admin/dashboard/verify'
    | '/admin/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claim'
    | '/report'
    | '/claim/claimForm'
    | '/footer/routes'
    | '/header/routes'
    | '/home/routes'
    | '/report-form/routes'
    | '/admin'
    | '/admin/dashboard/reports'
    | '/admin/dashboard/verify'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/claim'
    | '/report'
    | '/claim/claimForm'
    | '/footer/routes'
    | '/header/routes'
    | '/home/routes'
    | '/report-form/routes'
    | '/admin/'
    | '/admin/dashboard/reports'
    | '/admin/dashboard/verify'
    | '/admin/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaimRouteRoute: typeof ClaimRouteRouteWithChildren
  ReportRoute: typeof ReportRoute
  FooterRoutesRoute: typeof FooterRoutesRoute
  HeaderRoutesRoute: typeof HeaderRoutesRoute
  HomeRoutesRoute: typeof HomeRoutesRoute
  ReportFormRoutesRoute: typeof ReportFormRoutesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDashboardReportsRoute: typeof AdminDashboardReportsRoute
  AdminDashboardVerifyRoute: typeof AdminDashboardVerifyRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-form/routes': {
      id: '/report-form/routes'
      path: '/report-form/routes'
      fullPath: '/report-form/routes'
      preLoaderRoute: typeof ReportFormRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/routes': {
      id: '/home/routes'
      path: '/home/routes'
      fullPath: '/home/routes'
      preLoaderRoute: typeof HomeRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/header/routes': {
      id: '/header/routes'
      path: '/header/routes'
      fullPath: '/header/routes'
      preLoaderRoute: typeof HeaderRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer/routes': {
      id: '/footer/routes'
      path: '/footer/routes'
      fullPath: '/footer/routes'
      preLoaderRoute: typeof FooterRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/claimForm': {
      id: '/claim/claimForm'
      path: '/claimForm'
      fullPath: '/claim/claimForm'
      preLoaderRoute: typeof ClaimClaimFormRouteImport
      parentRoute: typeof ClaimRouteRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/verify': {
      id: '/admin/dashboard/verify'
      path: '/admin/dashboard/verify'
      fullPath: '/admin/dashboard/verify'
      preLoaderRoute: typeof AdminDashboardVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/reports': {
      id: '/admin/dashboard/reports'
      path: '/admin/dashboard/reports'
      fullPath: '/admin/dashboard/reports'
      preLoaderRoute: typeof AdminDashboardReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClaimRouteRouteChildren {
  ClaimClaimFormRoute: typeof ClaimClaimFormRoute
}

const ClaimRouteRouteChildren: ClaimRouteRouteChildren = {
  ClaimClaimFormRoute: ClaimClaimFormRoute,
}

const ClaimRouteRouteWithChildren = ClaimRouteRoute._addFileChildren(
  ClaimRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaimRouteRoute: ClaimRouteRouteWithChildren,
  ReportRoute: ReportRoute,
  FooterRoutesRoute: FooterRoutesRoute,
  HeaderRoutesRoute: HeaderRoutesRoute,
  HomeRoutesRoute: HomeRoutesRoute,
  ReportFormRoutesRoute: ReportFormRoutesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDashboardReportsRoute: AdminDashboardReportsRoute,
  AdminDashboardVerifyRoute: AdminDashboardVerifyRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
