/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClaimIndexRouteImport } from './routes/claim/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ClaimFoundFormRouteImport } from './routes/claim/foundForm'
import { Route as ClaimClaimFormRouteImport } from './routes/claim/claimForm'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminDashboardVerifyRouteImport } from './routes/admin/dashboard/verify'
import { Route as AdminDashboardReturnedRouteImport } from './routes/admin/dashboard/returned'
import { Route as AdminDashboardReportsRouteImport } from './routes/admin/dashboard/reports'
import { Route as AdminDashboardFoundItemsRouteImport } from './routes/admin/dashboard/found-items'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimIndexRoute = ClaimIndexRouteImport.update({
  id: '/claim/',
  path: '/claim/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimFoundFormRoute = ClaimFoundFormRouteImport.update({
  id: '/claim/foundForm',
  path: '/claim/foundForm',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimClaimFormRoute = ClaimClaimFormRouteImport.update({
  id: '/claim/claimForm',
  path: '/claim/claimForm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/admin/dashboard/',
  path: '/admin/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardVerifyRoute = AdminDashboardVerifyRouteImport.update({
  id: '/admin/dashboard/verify',
  path: '/admin/dashboard/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardReturnedRoute = AdminDashboardReturnedRouteImport.update({
  id: '/admin/dashboard/returned',
  path: '/admin/dashboard/returned',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardReportsRoute = AdminDashboardReportsRouteImport.update({
  id: '/admin/dashboard/reports',
  path: '/admin/dashboard/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardFoundItemsRoute =
  AdminDashboardFoundItemsRouteImport.update({
    id: '/admin/dashboard/found-items',
    path: '/admin/dashboard/found-items',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/report': typeof ReportRoute
  '/claim/claimForm': typeof ClaimClaimFormRoute
  '/claim/foundForm': typeof ClaimFoundFormRoute
  '/admin/': typeof AdminIndexRoute
  '/claim/': typeof ClaimIndexRoute
  '/admin/dashboard/found-items': typeof AdminDashboardFoundItemsRoute
  '/admin/dashboard/reports': typeof AdminDashboardReportsRoute
  '/admin/dashboard/returned': typeof AdminDashboardReturnedRoute
  '/admin/dashboard/verify': typeof AdminDashboardVerifyRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/report': typeof ReportRoute
  '/claim/claimForm': typeof ClaimClaimFormRoute
  '/claim/foundForm': typeof ClaimFoundFormRoute
  '/admin': typeof AdminIndexRoute
  '/claim': typeof ClaimIndexRoute
  '/admin/dashboard/found-items': typeof AdminDashboardFoundItemsRoute
  '/admin/dashboard/reports': typeof AdminDashboardReportsRoute
  '/admin/dashboard/returned': typeof AdminDashboardReturnedRoute
  '/admin/dashboard/verify': typeof AdminDashboardVerifyRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/report': typeof ReportRoute
  '/claim/claimForm': typeof ClaimClaimFormRoute
  '/claim/foundForm': typeof ClaimFoundFormRoute
  '/admin/': typeof AdminIndexRoute
  '/claim/': typeof ClaimIndexRoute
  '/admin/dashboard/found-items': typeof AdminDashboardFoundItemsRoute
  '/admin/dashboard/reports': typeof AdminDashboardReportsRoute
  '/admin/dashboard/returned': typeof AdminDashboardReturnedRoute
  '/admin/dashboard/verify': typeof AdminDashboardVerifyRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/report'
    | '/claim/claimForm'
    | '/claim/foundForm'
    | '/admin/'
    | '/claim/'
    | '/admin/dashboard/found-items'
    | '/admin/dashboard/reports'
    | '/admin/dashboard/returned'
    | '/admin/dashboard/verify'
    | '/admin/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/report'
    | '/claim/claimForm'
    | '/claim/foundForm'
    | '/admin'
    | '/claim'
    | '/admin/dashboard/found-items'
    | '/admin/dashboard/reports'
    | '/admin/dashboard/returned'
    | '/admin/dashboard/verify'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/report'
    | '/claim/claimForm'
    | '/claim/foundForm'
    | '/admin/'
    | '/claim/'
    | '/admin/dashboard/found-items'
    | '/admin/dashboard/reports'
    | '/admin/dashboard/returned'
    | '/admin/dashboard/verify'
    | '/admin/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ReportRoute: typeof ReportRoute
  ClaimClaimFormRoute: typeof ClaimClaimFormRoute
  ClaimFoundFormRoute: typeof ClaimFoundFormRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ClaimIndexRoute: typeof ClaimIndexRoute
  AdminDashboardFoundItemsRoute: typeof AdminDashboardFoundItemsRoute
  AdminDashboardReportsRoute: typeof AdminDashboardReportsRoute
  AdminDashboardReturnedRoute: typeof AdminDashboardReturnedRoute
  AdminDashboardVerifyRoute: typeof AdminDashboardVerifyRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/': {
      id: '/claim/'
      path: '/claim'
      fullPath: '/claim/'
      preLoaderRoute: typeof ClaimIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/foundForm': {
      id: '/claim/foundForm'
      path: '/claim/foundForm'
      fullPath: '/claim/foundForm'
      preLoaderRoute: typeof ClaimFoundFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/claimForm': {
      id: '/claim/claimForm'
      path: '/claim/claimForm'
      fullPath: '/claim/claimForm'
      preLoaderRoute: typeof ClaimClaimFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/verify': {
      id: '/admin/dashboard/verify'
      path: '/admin/dashboard/verify'
      fullPath: '/admin/dashboard/verify'
      preLoaderRoute: typeof AdminDashboardVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/returned': {
      id: '/admin/dashboard/returned'
      path: '/admin/dashboard/returned'
      fullPath: '/admin/dashboard/returned'
      preLoaderRoute: typeof AdminDashboardReturnedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/reports': {
      id: '/admin/dashboard/reports'
      path: '/admin/dashboard/reports'
      fullPath: '/admin/dashboard/reports'
      preLoaderRoute: typeof AdminDashboardReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/found-items': {
      id: '/admin/dashboard/found-items'
      path: '/admin/dashboard/found-items'
      fullPath: '/admin/dashboard/found-items'
      preLoaderRoute: typeof AdminDashboardFoundItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ReportRoute: ReportRoute,
  ClaimClaimFormRoute: ClaimClaimFormRoute,
  ClaimFoundFormRoute: ClaimFoundFormRoute,
  AdminIndexRoute: AdminIndexRoute,
  ClaimIndexRoute: ClaimIndexRoute,
  AdminDashboardFoundItemsRoute: AdminDashboardFoundItemsRoute,
  AdminDashboardReportsRoute: AdminDashboardReportsRoute,
  AdminDashboardReturnedRoute: AdminDashboardReturnedRoute,
  AdminDashboardVerifyRoute: AdminDashboardVerifyRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
